DROP TYPE IF EXISTS grocery;

CREATE TYPE grocery AS ENUM(
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  price decimal(6,2) NOT NULL,
  date_added date default now(),
  checked boolean default false,
  category grocery NOT NULL
);